# Generated by Django 4.2.2 on 2023-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='menu item')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
