# Generated by Django 4.2.2 on 2023-07-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mainmenuitem_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenuitem',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
