# Generated by Django 4.2.2 on 2023-07-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mainmenuitem_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenuitem',
            options={'ordering': ('position',)},
        ),
    ]
