# Generated by Django 4.2.2 on 2023-07-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mainmenuitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=255)),
                ('reservations_phone', models.CharField(max_length=20)),
                ('reservations_email', models.EmailField(max_length=254)),
                ('opening_hours', models.TextField(max_length=255)),
                ('twitter_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('copyright_text', models.CharField(max_length=255)),
                ('credits_text', models.CharField(max_length=255)),
            ],
        ),
    ]
