# Generated by Django 4.2.2 on 2023-07-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='reservations_email',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='reservations_phone',
        ),
        migrations.AddField(
            model_name='footer',
            name='reservation',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright_text',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='footer',
            name='credits_text',
            field=models.TextField(max_length=255),
        ),
    ]
