# Generated by Django 4.2.2 on 2023-07-05 09:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_footer_reservations_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='footer',
            name='credits_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='footer',
            name='opening_hours',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='footer',
            name='reservation',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
