# Generated by Django 4.2.2 on 2023-07-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
    ]
